[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.11
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true
